<span style="color:red; font-size:24px">Mảng cắt lát NumPy</span>

In [1]:
# Cắt các phần tử có chỉ mục từ 1 đến 5 của mảng sau
import numpy as np
arr = np.array([1,2,4,5,6,7,8])
print(arr[1:5])

[2 4 5 6]


In [2]:
# Cắt các phần tử từ chỉ mục 4 đến cuối mảng
import numpy as np
arr = np.array([1,2,4,5,6,7,8])
print(arr[4:])

[6 7 8]


In [3]:
# Cắt các phần tử từ đầu đến chỉ mục 4
import numpy as np
arr = np.array([1,2,4,5,6,7,8])
print(arr[:4])

[1 2 4 5]


<span style="font-size: 30px;">Cắt lát tiêu cực</span>


In [4]:
# Cắt từ chỉ mục 3 từ cuối đén chỉ mục 1 từ cuối
import numpy as np
arr = np.array([1,2,4,5,6,7,8])
print(arr[-3:-1])

[6 7]


<span style="font-size: 30px;">Bước cắt</span>


In [5]:
# Trả về mọi phần tử khác từ chỉ mục 1 đến 5
import numpy as np
arr = np.array([1,2,4,5,6,7,8])
print(arr[1:5:2])

[2 5]


In [7]:
# Trả về mọi phần tử khác từ toàn bộ mảng
import numpy as np
arr = np.array([1,2,4,5,6,7,8])
print(arr[::2])

[1 4 6 8]


<span style="font-size: 30px;">Cắt mảng 2-D</span>


In [9]:
# từ phần tử thứ 2, cắt các phần tử từ chỉ mục 1 đến 4
import numpy as np
arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(arr[1, 1:4])

[ 8  9 10]


In [11]:
# Từ cả 2 phần tử trả về chỉ mục 2
import numpy as np
arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(arr[0:2, 2])

[3 9]


In [12]:
# Từ cả 2 phần tử , trả về chỉ mục từ 1 đến 4
import numpy as np
arr = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(arr[0:2, 1:4])

[[ 2  3  4]
 [ 8  9 10]]
