<span style="font-size: 30px;">Copy</span>


In [1]:
# Tạo 1 bản copy, thay thế mảng gốc và hiển thị cả 2 mảng
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


<span style="font-size: 30px;">Views</span>


In [2]:
# Tạo 1 chế độ xem, thay đổi mảng ban đầu và hiển thị cả 2 mảng
import numpy as np
arr = np.array([1,2,4,5])
x = arr.view()
arr[0] = 41

print(arr)
print(x)

[41  2  4  5]
[41  2  4  5]


In [3]:
# Thực hiện các thay đổi trong views

# Tạo chế độ xem, thay đổi chế độ xem và hiển thị cả 2 mảng
import numpy as np
arr = np.array([1,23,4,4,5])
x = arr.view()
arr[0] = 31

print(arr)
print(x)

[31 23  4  4  5]
[31 23  4  4  5]


In [4]:
# In ra giá truh của thuộc tính cơ sở để kiểm tra xem 1 mảng có sở hữu dữ liệu của nó hay không
# Trả về (None nếu nó sở hữu dữ liệu) và trả về (đối tượng gốc nếu đó là không sở hữu dữ liệu)
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
