<span style="font-size: 30px;">Lặp qua mảng NumPy</span>


In [1]:
# Lặp qua các phần tử của mảng NumPy
import numpy as np
arr = np.array([1,23,55,45])
for x in arr:
    print(x)

1
23
55
45


In [2]:
# Lặp qua các phần tử của mảng 2-D
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
# lặp lại trên từng phần tử vô hướng của mảng 2-D
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [8]:
# Lặp lại các phần tử của mảng 3-D
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)




[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [9]:
# lặp xuống các phầ tử vô hướng 
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


<span style="font-size: 30px;">Lặp lại mảng bằng nditer</span>


In [10]:
# lặp qua mảng 3-D sau:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [3]:
# lặp lại mảng với các kiểu dữ liệu khác nhau
 # lặp lại qua mảng dưới dạng chuỗi
import numpy as np
arr = np.array([1,2,3])
for x in np.nditer(arr, flags =["buffered"], op_dtypes=["S"]):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [6]:
# Lặp lại với kích thước bước khác nhau
 # lặp lại mọi phần tử vô hướng của mảng 2D bỏ qua 1 phần tử
import numpy as np
arr = np.array([[1,2,4,5],[6,7,8,9]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
4
6
8
