<span style="font-size: 25px;">Định hình lại mảng NumPy</span>


In [3]:
# Định hình lại từ 1-D sang 2-D
# VD: Chuyển đổi mảng 1-D thành mảng 2-D (12 phần từ từ mảng 1-D thành 4 mảng với mỗi mảng 3 phần tử)
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# Chuyển đổi mảng 1-D sang mảng 3-D (chiều ngoài cùng có 2 mảng chứa 2 mảng, mỗi mảng 3 phần tử)
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# Kiểm tra mảng trả về là bản sao hay chế độ xem
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr = arr.reshape(2,3,2)
print(newarr)
print(newarr.base)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# chuyển đổi mảng 1-D với 8 phần tử sang mảng 3-D với phần tử 2x2
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr= arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<span style="font-size: 30px;">Làm phẳng các mảng</span>


In [17]:
# làm phẳng các mảng có nghĩa là chuyển đổi mảng đa chiều thành mảng 1-D
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
