In [1]:
# Tạo một đối tượng ndarray NumPy
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# Sử dụng một bộ để tạo một mảng NumPy:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [4]:
# Mảng 0-D, hoặc Vô hướng, là các phần tử trong một mảng. Mỗi giá trị trong một mảng là một mảng 0-D.
  # Tạo một mảng 0-D với giá trị 42
import numpy as np
arr = np.array(42)
print(arr)
print("số chiều :", arr.ndim)

42
số chiều : 0


In [5]:
# Mảng 1-D Một mảng có mảng 0-D làm phần tử của nó được gọi là mảng đơn chiều hoặc mảng 1-D.
  # Tạo một mảng 1-D chứa các giá trị 1,2,3,4,5:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print("số chiều :", arr.ndim)

[1 2 3 4 5]
số chiều : 1


In [6]:
# Mảng 2-D Một mảng có mảng 1-D làm các phần tử của nó được gọi là mảng 2-D.
  # Tạo một mảng 2-D chứa hai mảng có giá trị 1,2,3 và 4,5,6:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("số chiều :", arr.ndim)

[[1 2 3]
 [4 5 6]]
số chiều : 2


In [7]:
# Mảng 3-D Một mảng có mảng 2-D (ma trận) làm các phần tử của nó được gọi là mảng 3-D.
  # Tạo một mảng 3D với hai mảng 2D, cả hai đều chứa hai mảng với giá trị 1,2,3 và 4,5,6:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print("số chiều :", arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
số chiều : 3


In [9]:
# Kiểm tra số lượng kích thước: ndim (Kiểm tra các mảng có bao nhiêu chiều:)
import numpy as np
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print("Số chiều :",a.ndim)
print("Số chiều :",b.ndim)
print("Số chiều :",c.ndim)
print("Số chiều :",d.ndim)

Số chiều : 0
Số chiều : 1
Số chiều : 2
Số chiều : 3


In [11]:
# Mảng nhiều chiều hơn (một mảng có thể có bất kỳ số lượng chiều nào, để xác định số chiều bằng cách lập luận : ndim)
  # Tạo 1 mảng 5 chiều và xác minh rằng nó có 5 chiều
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("Số chiều :", arr.ndim)

[[[[[1 2 3 4]]]]]
Số chiều : 5
