<span style="font-size:24px">Mảng bộ lọc</span>


In [2]:
# Tạo 1 mảng từ các phần tử trên chỉ mục 0 và 2
import numpy as np
arr = np.array([41,42,43,44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


<span style="font-size:24px">Tạo mảng bộ lọc</span>


In [ ]:
# Tạo 1 mảng bộ lọc sẽ chỉ trả về các giá trị cao hơn 42
import numpy as np
arr = np.array([41,42,43,44])
# Tạo 1 list rỗng
filter_arr = []
# đi qua từng phần tử trong arr
for x in arr:
    if x>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

In [4]:
# tạo 1 mảng bộ lọc sẽ chỉ trả về các phần tử chẵn từ bản gốc mảng
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
# tạo 1 list rỗng
filter_arr =[]
# đi qua từng phần tử trong arr
for x in arr:
    if x%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


<span style="font-size:24px">Tạo bộ lọc trực tiếp từ mảng</span>


In [5]:
# Tạo 1 mảng bộ lọc sẽ chỉ trả về các giá trị cao hơn 42
import numpy as np
arr = np.array([41,42,43,44,55])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True  True]
[43 44 55]


In [6]:
# Tạo 1 mảng bộ lọc sẽ chỉ trả về các phần tử chẵn từ mảng gốc
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
filter_arr = arr%2==0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
