<span style="font-size:24px">Nối mảng NumPy</span>


In [1]:
# nối 2 mảng
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,6,7])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 6 7]


In [7]:
# nối mảng 2-D dọc theo các hàng (trục =1)
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [8]:
# Nối mảng bằng các hàm ngăn xếp (xếp theo cột)
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2), axis= 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
# xếp chồng dọc theo hàng
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [10]:
# Xếp chồng dọc theo cột
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# xếp chồng dọc theo chiều cao (độ sâu)
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
