<span style="font-size:24px">Tìm kiếm mảng</span>


In [2]:
# Tìm các chỉ mục có giá trị là 4
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr ==4)
print(x)


(array([3, 5, 6]),)


In [23]:
# tìm các chỉ mục có giá trị chẵn
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr%2 ==0)
print(x)

(array([1, 3, 5, 6]),)


In [4]:
# tìm các chỉ mục có giá trị lẻ
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr%2 != 0)
print(x)

(array([0, 2, 4]),)


<span style="font-size:24px">Tìm kiếm được sắp xếp</span>


In [9]:
# tìm các chỉ mục nơi giá trị 7 sẽ được chèn vào (phần tử sẽ được chèn vào trước phần tử bằng nớ)
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

1


In [22]:
# tìm các chỉ mục nơi giá trị 7 sẽ được chèn vào, bắt đầu từ bên phải (phần tử sẽ được chèn vào sau phần tử bằng nớ)
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [26]:
# Tìm các chỉ mục nơi các giá trị 2, 5, 10 sẽ được chèn vào
import numpy as np
arr = np.array([1,6,8,9])
x = np.searchsorted(arr, [2,5,10])
print(x)

[1 1 4]
