<span style="font-size:24px">Sắp xếp mảng</span>


In [1]:
# sẮp xếp mảng
import numpy as np
arr = np.array([1,4,3,7,6])
print(np.sort(arr))

[1 3 4 6 7]


In [2]:
# sắp xếp mảng theo thứ tự bảng chữ cái
import numpy as np
arr = np.array(["apple", "cherry", "banana", "orange"])
print(np.sort(arr))

['apple' 'banana' 'cherry' 'orange']


In [6]:
# sắp xếp 1 mảng Boolean
import numpy as np
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


<span style="font-size:24px">Sắp xếp mảng 2-D</span>



In [7]:
# sắp xếp mảng 2-D
import numpy as np
arr = np.array([[7,1,4],[3,0,2]])
print(np.sort(arr))

[[1 4 7]
 [0 2 3]]
